### ISSUE TITLE
Issue in Prjected band structure.

### ISSUE THREAD

**Issue by Ashutosh23M** [AdityaRoy-1996/Projected-Bands-in-Quantum-Espresso#4]
Hi i am using your code for fat band calculation. BUt am getting some error in QE-7.2 version:
That is; 
ashutosh@Ashutosh:~/CsSnI3-Cubic/GGA/ftband$ python3 band_projection.py
The Fermi Level is at     3.9477  eV is subtracted in plots
Traceback (most recent call last):
  File "/home/ashutosh/CsSnI3-Cubic/GGA/ftband/band_projection.py", line 1250, in <module>
    project_bands( 
  File "/home/ashutosh/CsSnI3-Cubic/GGA/ftband/band_projection.py", line 1070, in project_bands
    knames          =   read_kpoints(bands_in) 
  File "/home/ashutosh/CsSnI3-Cubic/GGA/ftband/band_projection.py", line 540, in read_kpoints
    kname   =   r'$' + kpoints[i].split()[-1].split('!')[1] + '$'
IndexError: list index out of range

But when i use it in QE 7.0 the code is working.
can you please help me out how to rectify this.

**Comment by AdityaRoy-1996** [comment]
Please provide me your input files.

**Comment by AdityaRoy-1996** [comment]
> Hi i am using your code for fat band calculation. BUt am getting some error in QE-7.2 version: That is; ashutosh@Ashutosh:~/CsSnI3-Cubic/GGA/ftband$ python3 band_projection.py The Fermi Level is at 3.9477 eV is subtracted in plots Traceback (most recent call last): File "/home/ashutosh/CsSnI3-Cubic/GGA/ftband/band_projection.py", line 1250, in project_bands( File "/home/ashutosh/CsSnI3-Cubic/GGA/ftband/band_projection.py", line 1070, in project_bands knames = read_kpoints(bands_in) File "/home/ashutosh/CsSnI3-Cubic/GGA/ftband/band_projection.py", line 540, in read_kpoints kname = r'$' + kpoints[i].split()[-1].split('!')[1] + '$' IndexError: list index out of range
> 
> But when i use it in QE 7.0 the code is working. can you please help me out how to rectify this.

Please provide me your input files.

**Comment by Ashutosh23M** [comment]
[CsSnI3.txt](https://github.com/AdityaRoy-1996/Projected-Bands-in-Quantum-Espresso/files/12535708/CsSnI3.txt)
this is the scf input file.

I ama using QE.7.2 and python Python 3.10.12. as python 3.8 is no more supporting.

**Comment by Ashutosh23M** [comment]
And thank you very much for your quick reply.

**Comment by AdityaRoy-1996** [comment]
> [CsSnI3.txt](https://github.com/AdityaRoy-1996/Projected-Bands-in-Quantum-Espresso/files/12535708/CsSnI3.txt) this is the scf input file.
> 
> I ama using QE.7.2 and python Python 3.10.12. as python 3.8 is no more supporting.

Actually its not python or QE problem, the way bands.in files is written.

This is my file that is working (Kpoints only)

K_POINTS crystal_b
4
    0.0000000000     0.0000000000     0.0000000000   19  !\Gamma
    0.0000000000     0.5000000000     0.0000000000   19  !X 
    0.5000000000     0.5000000000     0.0000000000   19  !M 
    0.0000000000     0.0000000000     0.0000000000    0  !\Gamma

<img width="181" alt="image" src="https://github.com/AdityaRoy-1996/Projected-Bands-in-Quantum-Espresso/assets/57098889/26bd7cfa-e4da-4c86-9d3e-6656499a68be">

**Comment by Ashutosh23M** [comment]
thanks a lot sir. I could able to get the expected result. 
Can i get your mail Id to reach you for some doubts regarding DFT.

**Comment by AdityaRoy-1996** [comment]
> thanks a lot sir. I could able to get the expected result. Can i get your mail Id to reach you for some doubts regarding DFT.

roy.aditya.aditya@gmail.com

Thanks!
